joint_1:
  gear_ratio: 100.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 1.57
  max_accel_rad_s2: 15.7
  min_limit_rad: -1.484
  max_limit_rad: 1.484
  home_pos: 2058.805

joint_2:
  gear_ratio: 100.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 1.0
  max_accel_rad_s2: 10.0
  min_limit_rad: -0.785
  max_limit_rad: 0.785
  home_pos: -0.1985267

joint_3:
  gear_ratio: 101.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 1.3
  max_accel_rad_s2: 13.0
  min_limit_rad: -0.785
  max_limit_rad: 0.611
  home_pos: 2038.563

joint_4:
  gear_ratio: 80.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 2.0
  max_accel_rad_s2: 20.0
  min_limit_rad: -0.785
  max_limit_rad: 0.785
  home_pos: 2573.584

joint_5:
  gear_ratio: 51.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 2.35
  max_accel_rad_s2: 23.5
  min_limit_rad: -0.785
  max_limit_rad: 0.785
  home_pos: -0.1590015

joint_6:
  gear_ratio: 50.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 2.35
  max_accel_rad_s2: 23.5
  min_limit_rad: -3.142
  max_limit_rad: 3.142
  home_pos: 4089.085
