joint_1:
  gear_ratio: 100.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 3.14
  max_accel_rad_s2: 31.4
  min_limit_rad: -2.967
  max_limit_rad: 2.967
  home_pos: 1029.4025
  max_ferror_rad: 0.1

joint_2:
  gear_ratio: 100.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 2.09
  max_accel_rad_s2: 20.9
  min_limit_rad: -1.571
  max_limit_rad: 1.571
  home_pos: -0.09926335
  max_ferror_rad: 0.1

joint_3:
  gear_ratio: 101.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 2.62
  max_accel_rad_s2: 26.2
  min_limit_rad: -1.571
  max_limit_rad: 1.222
  home_pos: 1019.2815
  max_ferror_rad: 0.1

joint_4:
  gear_ratio: 80.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 3.93
  max_accel_rad_s2: 39.3
  min_limit_rad: -1.571
  max_limit_rad: 1.571
  home_pos: 1286.792
  max_ferror_rad: 0.1

joint_5:
  gear_ratio: 51.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 4.71
  max_accel_rad_s2: 47.1
  min_limit_rad: -1.571
  max_limit_rad: 1.571
  home_pos: -0.07950075
  max_ferror_rad: 0.1

joint_6:
  gear_ratio: 50.0
  steps_per_rev: 10000
  dirhold_ns: 125
  dirsetup_ns: 125
  steplen_ns: 125
  stepspace_ns: 125
  max_vel_rad_s: 4.71
  max_accel_rad_s2: 47.1
  min_limit_rad: -6.283
  max_limit_rad: 6.283
  home_pos: 2044.5425
  max_ferror_rad: 0.1
